### ISSUE TITLE
Change selection outline

### ISSUE THREAD

**Issue by FewerFlaws** [magneticflux-/fabric-diagonal-panes#23] opened 2020-12-22 10:34 UTC
When mousing over the panes an outline of the old frame (with corners) is shown as if the frame wasn't diagonal at all.  I would not be surprised if this is related to the hitbox issue.  Since I'm not sure about that one way or another I'm reporting it as a separate issue =]

**Comment by magneticflux-** [comment] 2020-12-22 17:10
Yep, I should get around to implementing that...
I'll start poking around and probably release something soon.

The bounding boxes are linked to hitboxes, so I'll close this as a duplicate.

**Comment by magneticflux-** [comment] 2020-12-22 17:10
Duplicate of #4

**Closed as completed by magneticflux-** 2020-12-22 17:10 UTC
Labels: duplicate
